import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Link Sharing App",
  description: "Generated by Kowshik Shikder F",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      {/* <!-- FOR FONT AWASOME --> */}
      <script src="https://kit.fontawesome.com/e3eef4a801.js" crossorigin="anonymous"></script>
      <script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-storage.js"></script>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
